FROM node:15.2.1-alpine3.12 AS build

COPY . /build
WORKDIR /build

RUN npm install

ARG BACKEND_URL=http://localhost:8762/

ENV REACT_ENV_BACKEND_URL ${BACKEND_URL}

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /build/build /etc/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
