version: "3"

services:
  csharp-be:
    build:
      context: ./csharp_backend/csharp_backend_fidget_spinners
      dockerfile: Dockerfile.dev
    tty: true
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - ./csharp_backend/csharp_backend_fidget_spinners/Controller:/app/Controller
      - ./csharp_backend/csharp_backend_fidget_spinners/Models:/app/Models
      - ./csharp_backend/csharp_backend_fidget_spinners/Services:/app/Services
  fe-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        BACKEND_URL: java-prod:3000 # can be just exposed
    ports:
      - 8080:80
  eureka:
    image: springcloud/eureka
    expose:
      - 8761

  # java-prod:
  #   env:
  #     EUREKA_HOST: eureka:8761

# TODO: add Java and FE prod services
